language: java
jdk:
- oraclejdk7
script:
- travis_retry mvn clean install site
- "[ ${TRAVIS_PULL_REQUEST} = 'false' ] && mvn clean deploy --settings .travis/settings.xml"
notifications:
  slack: av-fitt:FmLx2wj2Td3cNfmrjaQXUXBO
  email:
  - alexander.willner@tu-berlin.de
  - fiteagle.dev@av.tu-berlin.de
cache:
  directories:
  - $HOME/.m2
env:
  global:
  - secure: sl1oJ++j0OupLfa9Ln8Vw4cyWSXjKAYnpwloej3/hzuTb2gd9j41gFKuumkz6xsKWDWGlhJR8pSoKRcJpydXZfGjphrQfIliyoJ+Zw1E1FXj72SUOASuf2r6MXp/4Pd7K7MDdITXzmxIoLA9C2NRfMzOkneCJcO94j24W9M/sKM=
  - secure: ZNX6Db1aC21zrmQIqhSWVtrTg50lC6q07xYQT3uv/b8wMiNA2YiZ7M6g9Lgn5XgngV28/h2VIkBEOQDwaeSeC87VTD84ipo+UeNThcciXbnSmEA6nUd0zr1zTcuu3ZWvscgbJ5Mu6d/8tNxp0WLXo+oDmYB+vWqhQ40rXW4qDwE=
after_success:
- curl http://demo.fiteagle.org/trigger.php?c=fiteagle
